export const translations = {
  en: {
    title: 'GPT-4o Images Gallery',
    subtitle: 'Curated collection of AI-generated images',
    search: 'Search...',
    filter: 'Filter',
    author: 'Author',
    tool: 'Creation Tool',
    viewDetails: 'View Details',
    backToGallery: 'Back to Gallery',
    prompt: 'Prompt',
    sourceLink: 'Source Link',
    promptNote: 'Note',
    referenceNote: 'Reference Image Required',
    submitter: 'Submitter',
    loading: 'Loading...',
    error: 'Error loading data',
    noResults: 'No results found',
    caseNumber: 'Case',
    by: 'by',
    showMore: 'Show More',
    showLess: 'Show Less',
    copyPrompt: 'Copy Prompt',
    promptCopied: 'Prompt copied!',
  },
  zh: {
    title: 'GPT-4o 图片精选',
    subtitle: '精选的 AI 生成图像合集',
    search: '搜索...',
    filter: '筛选',
    author: '作者',
    tool: '创作工具',
    viewDetails: '查看详情',
    backToGallery: '返回画廊',
    prompt: '提示词',
    sourceLink: '原文链接',
    promptNote: '注意',
    referenceNote: '需上传参考图片',
    submitter: '案例提交',
    loading: '加载中...',
    error: '加载数据时出错',
    noResults: '未找到结果',
    caseNumber: '案例',
    by: '作者',
    showMore: '显示更多',
    showLess: '显示更少',
    copyPrompt: '复制提示词',
    promptCopied: '提示词已复制！',
  },
};

